web:
  build: .
  links:
   - memcache
   - couchdb
   - redis
  ports:
   - "5000:5000"
memcache:
  image: memcached
couchdb:
  image: tutum/couchdb
  ports:
   - "5984:5984"
  environment:
   - COUCHDB_PASS=admin
redis:
  image: redis
  ports:
   - "6379:6379"
